#ifndef _ISR_H
#define _ISR_H
void isr_int_0(void);
void isr_int_1(void);
void isr_int_10(void);
void isr_int_11(void);
void isr_int_12(void);
void isr_int_13(void);
void isr_int_14(void);
void isr_int_16(void);
void isr_int_17(void);
void isr_int_18(void);
void isr_int_19(void);
void isr_int_2(void);
void isr_int_3(void);
void isr_int_32(void);
void isr_int_33(void);
void isr_int_34(void);
void isr_int_35(void);
void isr_int_36(void);
void isr_int_37(void);
void isr_int_38(void);
void isr_int_39(void);
void isr_int_4(void);
void isr_int_40(void);
void isr_int_5(void);
void isr_int_6(void);
void isr_int_7(void);
void isr_int_8(void);
void isr_int_9(void);
void isr_timer(void);
#endif /* _ISR_H_ */
